# Generated by Django 3.1 on 2020-11-07 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prime_date_api', '0003_auto_20201107_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='name',
        ),
    ]
