# Generated by Django 3.1 on 2020-11-07 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prime_date_api', '0004_remove_mymodel_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mymodel',
            table='MyModel',
        ),
    ]
