# Generated by Django 3.1 on 2020-11-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime_date_api', '0006_auto_20201107_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
